# syntax=docker/dockerfile:1

FROM python:3.9.6-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . /usr/src/app

RUN docker run -p 6379:6379 -d redis:5

EXPOSE 8000

CMD [ "python", "manage.py" , "runserver", "0.0.0.0:8000"]