# Generated by Django 3.2.6 on 2021-08-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_collection',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
    ]
